// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAu5A2IHxPA4gqHCOxVm-_JwSTUj92iYDc',
//     appId: '1:887377476152:web:26c62565bdeb3ad8dc84cd',
//     messagingSenderId: '887377476152',
//     projectId: 'personal-financial-app2',
//     authDomain: 'personal-financial-app2.firebaseapp.com',
//     storageBucket: 'personal-financial-app2.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCyGAhzwzNnbB3lOj5j3qWtZPZGeKu2A_U',
//     appId: '1:887377476152:android:3db2535b2619a025dc84cd',
//     messagingSenderId: '887377476152',
//     projectId: 'personal-financial-app2',
//     storageBucket: 'personal-financial-app2.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC3dpZqIKKs-1dP-6Ib9bnUYSwidwl2J1A',
//     appId: '1:887377476152:ios:284188da07a03450dc84cd',
//     messagingSenderId: '887377476152',
//     projectId: 'personal-financial-app2',
//     storageBucket: 'personal-financial-app2.firebasestorage.app',
//     iosBundleId: 'com.example.personalFinancialApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyC3dpZqIKKs-1dP-6Ib9bnUYSwidwl2J1A',
//     appId: '1:887377476152:ios:284188da07a03450dc84cd',
//     messagingSenderId: '887377476152',
//     projectId: 'personal-financial-app2',
//     storageBucket: 'personal-financial-app2.firebasestorage.app',
//     iosBundleId: 'com.example.personalFinancialApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAu5A2IHxPA4gqHCOxVm-_JwSTUj92iYDc',
//     appId: '1:887377476152:web:5a016ceb5e36d094dc84cd',
//     messagingSenderId: '887377476152',
//     projectId: 'personal-financial-app2',
//     authDomain: 'personal-financial-app2.firebaseapp.com',
//     storageBucket: 'personal-financial-app2.firebasestorage.app',
//   );
// }
